title: Libix's Blog
description: 记录学习与生活
url: "https://librebitx.github.io"
baseurl: ""
show_downloads: false

theme: minima

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge
